export const selectors = {
    listItems : document.querySelector('[data-list-items]'),
    searchGenres : document.querySelector('[data-search-genres]'),
    searchAuthors : document.querySelector('[data-search-authors]'),
    settingsTheme : document.querySelector('[data-settings-theme]'),
    listButton : document.querySelector('[data-list-button]'),
    searchCancel : document.querySelector('[data-search-cancel]'),
    searchOverlay : document.querySelector('[data-search-overlay]'),
    headerSearch : document.querySelector('[data-header-search]'),
    headerSettings : document.querySelector('[data-header-settings]'),
    searchTitle : document.querySelector('[data-search-title]'),
    settingsOverlay : document.querySelector('[data-settings-overlay]'),
    listClose : document.querySelector('[data-list-close]'),
    listActive : document.querySelector('[data-list-active]'),
    searchForm : document.querySelector('[data-search-form]'),
    settingsForm : document.querySelector('[data-settings-form]'),
    settingsCancel: document.querySelector('[data-settings-cancel]'),
    listMessage : document.querySelector('[data-list-message]'),
    listDescription : document.querySelector('[data-list-description]'),
    listBlur : document.querySelector('[data-list-blur]'),
    listImage : document.querySelector('[data-list-image]'),
    listSubtitle : document.querySelector('[data-list-subtitle]'),
    listTitle : document.querySelector('[data-list-title]'),
    save : document.querySelector('[form="settings"]'),
}